# Check shell scripts with ShellCheck
# NOTE: ShellCheck must be available in the command search PATHs
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.0.0
  hooks:
    - id: shellcheck
